In [1]:
import pandas as pd

df = pd.read_csv('customer_shopping_behavior.csv')

In [3]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [8]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [10]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [16]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [17]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [19]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [21]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [23]:
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [25]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [28]:
# create age_group column
labels = ['Young Adult', 'Adult', 'Middle-Aged', 'Senior']
df['age_group'] =pd.qcut(df['age'], q=4, labels=labels)

In [31]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-Aged
1   19  Young Adult
2   50  Middle-Aged
3   21  Young Adult
4   45  Middle-Aged
5   46  Middle-Aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-Aged

In [42]:
#create column purchase_freaquency_day
frequency_mapping = {'Fortnightly' : 14,
                      'Weekly' : 7,
                      'Monthly' : 30,
                      'Quarterly' : 90,
                      'Bi-Weekly' : 14,
                      'Annually' : 365,
                      'Everey 3 Months' : 90}
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

df[['purchase_frequency_days', 'frequency_of_purchases']].head(10)

In [44]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                    365.0               Annually
5                      7.0                 Weekly
6                     90.0              Quarterly
7                      7.0                 Weekly
8                    365.0               Annually
9                     90.0              Quarterly

In [46]:
#'discount_applied', 'promo_code_used',
df[['discount_applied', 'promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [82]:
(df['discount_applied'] == df['promo_code_used']).all()

KeyError: 'promo_code_used'

In [81]:
df = df.drop(columns=[ 'promo_code_used'])

KeyError: "['promo_code_used'] not found in axis"

In [89]:
!pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in c:\users\administrator\appdata\local\programs\python\python314\lib\site-packages (1.1.2)
Requirement already satisfied: sqlalchemy in c:\users\administrator\appdata\local\programs\python\python314\lib\site-packages (2.0.46)
Requirement already satisfied: greenlet>=1 in c:\users\administrator\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\administrator\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy) (4.15.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [102]:
from sqlalchemy import create_engine

# My Connection
username = 'root'
password = 'Surendra@9123'
host = 'localhost'
port = '3306'
database = 'customer_behavier'

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

#write data frame to my sql

table_name ='customers_data'
df.to_sql(table_name, engine, if_exists='replace', index=False)

#read back simple
pd.read_sql("SELECT * FROM customer_behavier LIMIT 5;", engine)

OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '9123@localhost' ([Errno 11003] getaddrinfo failed)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [105]:
import pandas as pd
from sqlalchemy import create_engine

# 1. Connection Details
username = 'root'
password = 'Surendra@9123'
host     = 'localhost'
port     = '3306'
database = 'customer_behavier'

# 2. Create Engine (Updated to use mysql-connector)
engine = create_engine(f"mysql+mysqlconnector://{username}:{password}@{host}:{port}/{database}")

# 3. Write DataFrame to MySQL
table_name = 'customers_data'
df.to_sql(table_name, con=engine, if_exists='replace', index=False)
print(f"Success: Data written to table '{table_name}'")

# 4. Read back (Fixed the table name here)
# We query the TABLE name 'customers_data', not the database name.
df_from_db = pd.read_sql(f"SELECT * FROM {table_name} LIMIT 5;", con=engine)

print(df_from_db)

ModuleNotFoundError: No module named 'mysql'

In [2]:
df.to_csv('customer_shopping_behavior.csv', index=False)

print("File saved successfully!")

File saved successfully!

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              3900 non-null   int64
 1   age                      3900 non-null   int64
 2   gender                   3900 non-null   str
 3   item_purchased           3900 non-null   str
 4   category                 3900 non-null   str
 5   purchase_amount          3900 non-null   int64
 6   location                 3900 non-null   str
 7   size                     3900 non-null   str
 8   color                    3900 non-null   str
 9   season                   3900 non-null   str
 10  review_rating            3900 non-null   float64
 11  subscription_status      3900 non-null   str
 12  shipping_type            3900 non-null   str
 13  discount_applied         3900 non-null   str
 14  previous_purchases       3900 non-null   int64
 15  payment_method           3900 non-null   str
 16  frequency_of_purchases   3900 non-null   str
 17  age_group                3900 non-null   str
 18  pruchase_frequency_day   3316 non-null   float64
 19  pruchase_frequency_days  3316 non-null   float64
 20  purchase_frequency_days  3316 non-null   float64
dtypes: float64(4), int64(4), str(13)
memory usage: 640.0 KB

In [5]:
df.head(10)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,...,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,pruchase_frequency_day,pruchase_frequency_days,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,...,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-Aged,14.0,14.0,14.0
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,...,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14.0,14.0,14.0
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,...,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-Aged,7.0,7.0,7.0
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,...,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7.0,7.0,7.0
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,...,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-Aged,365.0,365.0,365.0
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,...,Yes,Standard,Yes,14,Venmo,Weekly,Middle-Aged,7.0,7.0,7.0
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,...,Yes,Free Shipping,Yes,49,Cash,Quarterly,Senior,90.0,90.0,90.0
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,...,Yes,Free Shipping,Yes,19,Credit Card,Weekly,Young Adult,7.0,7.0,7.0
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,...,Yes,Express,Yes,8,Venmo,Annually,Young Adult,365.0,365.0,365.0
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,...,Yes,2-Day Shipping,Yes,4,Cash,Quarterly,Middle-Aged,90.0,90.0,90.0

In [7]:
df = df.drop(columns=['purchase_frequency_days'])

KeyError: "['purchase_frequency_days'] not found in axis"

In [84]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'pruchase_frequency_day',
       'pruchase_frequency_days', 'purchase_frequency_days'],
      dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              3900 non-null   int64
 1   age                      3900 non-null   int64
 2   gender                   3900 non-null   str
 3   item_purchased           3900 non-null   str
 4   category                 3900 non-null   str
 5   purchase_amount          3900 non-null   int64
 6   location                 3900 non-null   str
 7   size                     3900 non-null   str
 8   color                    3900 non-null   str
 9   season                   3900 non-null   str
 10  review_rating            3900 non-null   float64
 11  subscription_status      3900 non-null   str
 12  shipping_type            3900 non-null   str
 13  discount_applied         3900 non-null   str
 14  previous_purchases       3900 non-null   int64
 15  payment_method           3900 non-null   str
 16  frequency_of_purchases   3900 non-null   str
 17  age_group                3900 non-null   str
 18  pruchase_frequency_day   3316 non-null   float64
 19  pruchase_frequency_days  3316 non-null   float64
dtypes: float64(3), int64(4), str(13)
memory usage: 609.5 KB

In [11]:
df = df.drop(columns=['purchase_frequency_day'])

KeyError: "['purchase_frequency_day'] not found in axis"

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              3900 non-null   int64
 1   age                      3900 non-null   int64
 2   gender                   3900 non-null   str
 3   item_purchased           3900 non-null   str
 4   category                 3900 non-null   str
 5   purchase_amount          3900 non-null   int64
 6   location                 3900 non-null   str
 7   size                     3900 non-null   str
 8   color                    3900 non-null   str
 9   season                   3900 non-null   str
 10  review_rating            3900 non-null   float64
 11  subscription_status      3900 non-null   str
 12  shipping_type            3900 non-null   str
 13  discount_applied         3900 non-null   str
 14  previous_purchases       3900 non-null   int64
 15  payment_method           3900 non-null   str
 16  frequency_of_purchases   3900 non-null   str
 17  age_group                3900 non-null   str
 18  pruchase_frequency_day   3316 non-null   float64
 19  pruchase_frequency_days  3316 non-null   float64
dtypes: float64(3), int64(4), str(13)
memory usage: 609.5 KB

In [13]:
df.head(10)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,pruchase_frequency_day,pruchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-Aged,14.0,14.0
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14.0,14.0
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-Aged,7.0,7.0
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7.0,7.0
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-Aged,365.0,365.0
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,14,Venmo,Weekly,Middle-Aged,7.0,7.0
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,49,Cash,Quarterly,Senior,90.0,90.0
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,19,Credit Card,Weekly,Young Adult,7.0,7.0
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,8,Venmo,Annually,Young Adult,365.0,365.0
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,4,Cash,Quarterly,Middle-Aged,90.0,90.0

In [14]:
df.columns = df.columns.str.replace('pruchase_frequency_days','pruchase_frequency_day')

In [17]:
df.head(10)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,pruchase_frequency_day,pruchase_frequency_day
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-Aged,14.0,14.0
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14.0,14.0
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-Aged,7.0,7.0
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7.0,7.0
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-Aged,365.0,365.0
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,14,Venmo,Weekly,Middle-Aged,7.0,7.0
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,49,Cash,Quarterly,Senior,90.0,90.0
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,19,Credit Card,Weekly,Young Adult,7.0,7.0
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,8,Venmo,Annually,Young Adult,365.0,365.0
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,4,Cash,Quarterly,Middle-Aged,90.0,90.0

In [21]:
df.T.drop_duplicates().T

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,pruchase_frequency_day
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-Aged,14.0
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14.0
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-Aged,7.0
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7.0
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-Aged,365.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,32,Venmo,Weekly,Adult,7.0
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,41,Bank Transfer,Bi-Weekly,Middle-Aged,14.0
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,24,Venmo,Quarterly,Middle-Aged,90.0
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,24,Venmo,Weekly,Adult,7.0
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,33,Venmo,Quarterly,Middle-Aged,90.0

In [23]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'pruchase_frequency_day',
       'pruchase_frequency_day'],
      dtype='str')

In [24]:
df.head(5)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,pruchase_frequency_day,pruchase_frequency_day
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-Aged,14.0,14.0
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14.0,14.0
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-Aged,7.0,7.0
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7.0,7.0
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-Aged,365.0,365.0

In [25]:
df = df.loc[:, ~df.columns.duplicated()]

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             3900 non-null   int64
 1   age                     3900 non-null   int64
 2   gender                  3900 non-null   str
 3   item_purchased          3900 non-null   str
 4   category                3900 non-null   str
 5   purchase_amount         3900 non-null   int64
 6   location                3900 non-null   str
 7   size                    3900 non-null   str
 8   color                   3900 non-null   str
 9   season                  3900 non-null   str
 10  review_rating           3900 non-null   float64
 11  subscription_status     3900 non-null   str
 12  shipping_type           3900 non-null   str
 13  discount_applied        3900 non-null   str
 14  previous_purchases      3900 non-null   int64
 15  payment_method          3900 non-null   str
 16  frequency_of_purchases  3900 non-null   str
 17  age_group               3900 non-null   str
 18  pruchase_frequency_day  3316 non-null   float64
dtypes: float64(2), int64(4), str(13)
memory usage: 579.0 KB

In [30]:
!pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\administrator\appdata\local\programs\python\python314\lib\site-packages (2.0.46)
Requirement already satisfied: greenlet>=1 in c:\users\administrator\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\administrator\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy) (4.15.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [31]:
from sqlalchemy import create_engine

# Syntax: 'mysql+mysqlconnector://user:password@host/database'
engine = create_engine('mysql+mysqlconnector://root:password123@localhost/your_db_name')

# Send your DataFrame to a new table in MySQL
df.to_sql('customer_data', con=engine, if_exists='replace', index=False)

ModuleNotFoundError: No module named 'mysql'

In [32]:
from sqlalchemy import creat_engine

username = "root"
password = "Surendra@9123"
host = "localhost"
port = "3306"
database = "customer_behavier"

engine = create_engine(f"mysql+pymsql://{username}:{password}@{host}:{port}/{database}")

table_name = "customers"
df.to_sql(table_name, engine, if_exists="replace", index=False)

pd.read_sql("SELECT * FROM customers LIMIT 5;", engine)

ImportError: cannot import name 'creat_engine' from 'sqlalchemy' (C:\Users\Administrator\AppData\Local\Programs\Python\Python314\Lib\site-packages\sqlalchemy\__init__.py)

In [33]:
pip install pymysql

Requirement already satisfied: pymysql in c:\users\administrator\appdata\local\programs\python\python314\lib\site-packages (1.1.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [34]:
import pandas as pd
from sqlalchemy import create_engine  # Fixed 'create'

# Connection details
username = "root"
password = "Surendra@9123"
host = "localhost"
port = "3306"
database = "customer_behavier"

# Connection string: Fixed 'pymysql'
engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

# 1. Upload the data
table_name = "customers"
df.to_sql(table_name, engine, if_exists="replace", index=False)

# 2. Read it back to verify
# Note: Assign it to a variable to see the output clearly
df_from_db = pd.read_sql(f"SELECT * FROM {table_name} LIMIT 5;", engine)
print(df_from_db)

OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '9123@localhost' ([Errno 11003] getaddrinfo failed)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)